// This file was auto-generated. Do not edit
goog.addDependency('../../../javascript/atoms/action.js', ['bot.action'], ['bot', 'bot.Device', 'bot.Error', 'bot.ErrorCode', 'bot.Keyboard', 'bot.Mouse', 'bot.Touchscreen', 'bot.dom', 'bot.events', 'bot.events.EventType', 'goog.array', 'goog.math.Coordinate', 'goog.math.Vec2', 'goog.style'], false);
goog.addDependency('../../../javascript/atoms/bot.js', ['bot'], [], false);
goog.addDependency('../../../javascript/atoms/color.js', ['bot.color'], ['goog.array', 'goog.color.names'], false);
goog.addDependency('../../../javascript/atoms/device.js', ['bot.Device', 'bot.Device.EventEmitter'], ['bot', 'bot.dom', 'bot.locators', 'bot.userAgent', 'goog.array', 'goog.dom', 'goog.dom.TagName', 'goog.userAgent', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/atoms/dom.js', ['bot.dom'], ['bot', 'bot.color', 'bot.locators.xpath', 'bot.userAgent', 'goog.array', 'goog.dom', 'goog.dom.DomHelper', 'goog.dom.NodeType', 'goog.dom.TagName', 'goog.math', 'goog.math.Coordinate', 'goog.math.Rect', 'goog.string', 'goog.style', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/error.js', ['bot.Error', 'bot.ErrorCode'], [], false);
goog.addDependency('../../../javascript/atoms/events.js', ['bot.events', 'bot.events.EventArgs', 'bot.events.EventType', 'bot.events.KeyboardArgs', 'bot.events.MSGestureArgs', 'bot.events.MSPointerArgs', 'bot.events.MouseArgs', 'bot.events.Touch', 'bot.events.TouchArgs'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.userAgent', 'goog.array', 'goog.dom', 'goog.style', 'goog.userAgent', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/atoms/frame.js', ['bot.frame'], ['bot.Error', 'bot.locators', 'goog.dom', 'goog.dom.TagName'], false);
goog.addDependency('../../../javascript/atoms/inject.js', ['bot.inject', 'bot.inject.cache'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.json', 'bot.response.ResponseObject', 'goog.array', 'goog.dom.NodeType', 'goog.object', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/json.js', ['bot.json'], ['bot.userAgent', 'goog.json', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/keyboard.js', ['bot.Keyboard', 'bot.Keyboard.Key', 'bot.Keyboard.Keys'], ['bot.Device', 'bot.Error', 'bot.ErrorCode', 'bot.dom', 'bot.events.EventType', 'goog.array', 'goog.dom.TagName', 'goog.dom.selection', 'goog.structs.Map', 'goog.structs.Set', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/mouse.js', ['bot.Mouse', 'bot.Mouse.Button', 'bot.Mouse.State'], ['bot', 'bot.Device', 'bot.Error', 'bot.ErrorCode', 'bot.dom', 'bot.events.EventType', 'bot.userAgent', 'goog.dom', 'goog.dom.TagName', 'goog.math.Coordinate', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/response.js', ['bot.response', 'bot.response.ResponseObject'], ['bot.Error', 'bot.ErrorCode'], false);
goog.addDependency('../../../javascript/atoms/touchscreen.js', ['bot.Touchscreen'], ['bot', 'bot.Device', 'bot.Error', 'bot.ErrorCode', 'bot.dom', 'bot.events.EventType', 'goog.dom.TagName', 'goog.math.Coordinate', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/atoms/userAgent.js', ['bot.userAgent'], ['goog.string', 'goog.userAgent', 'goog.userAgent.product', 'goog.userAgent.product.isVersion'], false);
goog.addDependency('../../../javascript/atoms/window.js', ['bot.window'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.events', 'bot.userAgent', 'goog.dom', 'goog.dom.DomHelper', 'goog.math.Coordinate', 'goog.math.Size', 'goog.style', 'goog.userAgent', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/atoms/html5/appcache.js', ['bot.appcache'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.html5'], false);
goog.addDependency('../../../javascript/atoms/html5/database.js', ['bot.storage.database', 'bot.storage.database.ResultSet'], ['bot', 'bot.Error', 'bot.ErrorCode'], false);
goog.addDependency('../../../javascript/atoms/html5/html5_browser.js', ['bot.html5'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.userAgent', 'goog.userAgent', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/atoms/html5/location.js', ['bot.geolocation'], ['bot', 'bot.html5'], false);
goog.addDependency('../../../javascript/atoms/html5/storage.js', ['bot.storage', 'bot.storage.Storage'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.html5'], false);
goog.addDependency('../../../javascript/atoms/locators/classname.js', ['bot.locators.className'], ['bot.Error', 'bot.ErrorCode', 'goog.array', 'goog.dom', 'goog.dom.DomHelper', 'goog.string'], false);
goog.addDependency('../../../javascript/atoms/locators/css.js', ['bot.locators.css'], ['bot.Error', 'bot.ErrorCode', 'bot.userAgent', 'goog.dom.NodeType', 'goog.string', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/locators/id.js', ['bot.locators.id'], ['bot.dom', 'goog.array', 'goog.dom'], false);
goog.addDependency('../../../javascript/atoms/locators/link_text.js', ['bot.locators.linkText', 'bot.locators.partialLinkText'], ['bot', 'bot.dom', 'bot.locators.css', 'goog.array', 'goog.dom', 'goog.dom.DomHelper'], false);
goog.addDependency('../../../javascript/atoms/locators/locators.js', ['bot.locators'], ['bot', 'bot.locators.className', 'bot.locators.css', 'bot.locators.id', 'bot.locators.linkText', 'bot.locators.name', 'bot.locators.partialLinkText', 'bot.locators.tagName', 'bot.locators.xpath', 'goog.array', 'goog.object'], false);
goog.addDependency('../../../javascript/atoms/locators/name.js', ['bot.locators.name'], ['bot.dom', 'goog.array', 'goog.dom'], false);
goog.addDependency('../../../javascript/atoms/locators/tag_name.js', ['bot.locators.tagName'], ['goog.array'], false);
goog.addDependency('../../../javascript/atoms/locators/xpath.js', ['bot.locators.xpath'], ['bot', 'bot.Error', 'bot.ErrorCode', 'goog.array', 'goog.dom', 'goog.dom.NodeType', 'goog.userAgent', 'goog.userAgent.product', 'wgxpath'], false);
goog.addDependency('../../../javascript/atoms/test/jquery.min.js', [], [], false);
goog.addDependency('../../../javascript/atoms/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/atoms/test/test_util.js', ['bot.test'], ['bot.userAgent', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/atoms/test/text_util.js', [], ['bot.dom', 'goog.array', 'goog.dom', 'goog.dom.NodeType', 'goog.testing.TestCase'], false);
goog.addDependency('../../../javascript/atoms/test/useragent_test.js', [], ['goog.dom', 'goog.userAgent', 'goog.userAgent.product'], false);
goog.addDependency('../../../javascript/chrome-driver/atoms.js', ['webdriver.chrome'], ['bot.dom', 'bot.locators', 'goog.dom', 'goog.math.Coordinate', 'goog.math.Rect', 'goog.math.Size', 'goog.style'], false);
goog.addDependency('../../../javascript/chrome-driver/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/extension/components/httpd.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/extension/content/dommessenger.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/extension/content/server.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/badCertListener.js', ['WdCertOverrideService'], ['bot.userAgent', 'fxdriver.logging', 'fxdriver.moz', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/dispatcher.js', ['Dispatcher', 'Resource'], ['fxdriver.Request', 'fxdriver.Response', 'Utils', 'bot.ErrorCode', 'fxdriver.error', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/driver-component.js', [], ['WebDriverServer', 'WebElement', 'fxdriver.logging', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/element_cache.js', ['fxdriver.cache'], ['Utils', 'WebDriverError', 'bot.ErrorCode', 'fxdriver.moz', 'fxdriver.utils', 'goog.dom'], false);
goog.addDependency('../../../javascript/firefox-driver/js/error.js', ['fxdriver.error', 'WebDriverError'], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/evaluate.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/events.js', ['fxdriver.events'], ['Utils', 'fxdriver.moz', 'goog.style'], false);
goog.addDependency('../../../javascript/firefox-driver/js/exported_symbols.js', [], ['fxdriver.events', 'Dispatcher'], false);
goog.addDependency('../../../javascript/firefox-driver/js/externs.js', [], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/files.js', ['fxdriver.files', 'fxdriver.files.File'], ['WebDriverError', 'bot.ErrorCode'], false);
goog.addDependency('../../../javascript/firefox-driver/js/firefox-utils.js', ['fxdriver.utils'], ['bot.Error', 'bot.ErrorCode', 'bot.userAgent', 'fxdriver.moz', 'goog.array'], false);
goog.addDependency('../../../javascript/firefox-driver/js/firefoxDriver.js', ['FirefoxDriver'], ['Utils', 'WebLoadingListener', 'bot.ErrorCode', 'bot.appcache', 'bot.dom', 'bot.frame', 'bot.locators', 'bot.userAgent', 'bot.window', 'fxdriver.Timer', 'fxdriver.events', 'fxdriver.io', 'fxdriver.logging', 'fxdriver.modals', 'fxdriver.preconditions', 'fxdriver.screenshot', 'fxdriver.utils', 'goog.array', 'goog.dom', 'goog.dom.selection', 'goog.log', 'goog.math.Coordinate', 'goog.math.Size'], false);
goog.addDependency('../../../javascript/firefox-driver/js/logger.js', ['fxdriver.logging'], ['fxdriver.files.File', 'fxdriver.prefs', 'goog.array', 'goog.debug.TextFormatter', 'goog.log', 'goog.object', 'goog.string', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/firefox-driver/js/modals.js', ['fxdriver.modals'], ['WebDriverError', 'bot.ErrorCode', 'fxdriver.Timer', 'fxdriver.moz', 'fxdriver.utils', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/modifierKeys.js', ['ModifierKeys'], ['Utils', 'bot.Device', 'fxdriver.moz'], false);
goog.addDependency('../../../javascript/firefox-driver/js/moz.js', ['fxdriver.moz'], ['bot.userAgent', 'goog.array', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/nsCommandProcessor.js', ['fxdriver.CommandResponse'], ['FirefoxDriver', 'Utils', 'WebElement', 'bot.ErrorCode', 'bot.locators', 'bot.userAgent', 'fxdriver.Timer', 'fxdriver.error', 'fxdriver.logging', 'fxdriver.modals', 'fxdriver.moz', 'fxdriver.profiler', 'goog.array', 'goog.log', 'wdSessionStoreService'], false);
goog.addDependency('../../../javascript/firefox-driver/js/preconditions.js', ['fxdriver.preconditions'], ['Utils', 'bot.dom'], false);
goog.addDependency('../../../javascript/firefox-driver/js/prefs.js', ['fxdriver.prefs'], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/profiler.js', ['fxdriver.profiler'], ['fxdriver.logging', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/firefox-driver/js/promptService.js', [], ['fxdriver.modals', 'fxdriver.moz', 'goog.array', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/proxy.js', ['fxdriver.proxy', 'fxdriver.proxy.ProxyConfig'], ['fxdriver.logging', 'fxdriver.moz', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/request.js', ['fxdriver.Request'], ['Utils'], false);
goog.addDependency('../../../javascript/firefox-driver/js/response.js', ['fxdriver.Response'], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/screenshooter.js', ['fxdriver.screenshot'], ['fxdriver.moz'], false);
goog.addDependency('../../../javascript/firefox-driver/js/sessionstore.js', ['wdSessionStoreService'], ['fxdriver.logging', 'fxdriver.modals', 'fxdriver.moz', 'fxdriver.proxy', 'goog.log', 'goog.object', 'wdSession'], false);
goog.addDependency('../../../javascript/firefox-driver/js/syntheticMouse.js', ['SyntheticMouse'], ['Utils', 'bot.ErrorCode', 'bot.Mouse', 'bot.Device.EventEmitter', 'bot.action', 'bot.dom', 'bot.events', 'bot.events.EventType', 'bot.window', 'fxdriver.logging', 'fxdriver.moz', 'fxdriver.utils', 'goog.dom', 'goog.dom.TagName', 'goog.log', 'goog.math.Coordinate', 'goog.style'], false);
goog.addDependency('../../../javascript/firefox-driver/js/timer.js', ['fxdriver.Timer'], [], false);
goog.addDependency('../../../javascript/firefox-driver/js/utils.js', ['Utils'], ['WebLoadingListener', 'bot.ErrorCode', 'bot.dom', 'bot.userAgent', 'fxdriver.logging', 'fxdriver.moz', 'fxdriver.utils', 'fxdriver.error', 'goog.dom', 'goog.log', 'goog.string', 'goog.style'], false);
goog.addDependency('../../../javascript/firefox-driver/js/wdsession.js', ['wdSession'], ['fxdriver.logging', 'fxdriver.moz', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/webdriverserver.js', ['WebDriverServer'], ['Dispatcher', 'FirefoxDriver', 'Utils', 'WebElement', 'fxdriver.logging', 'fxdriver.moz', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/webLoadingListener.js', ['WebLoadingListener', 'fxdriver.io'], ['fxdriver.Timer', 'fxdriver.logging', 'fxdriver.moz', 'goog.log'], false);
goog.addDependency('../../../javascript/firefox-driver/js/wrappedElement.js', ['WebElement'], ['Utils', 'WebLoadingListener', 'bot.ErrorCode', 'bot.action', 'bot.dom', 'fxdriver.io', 'fxdriver.logging', 'fxdriver.moz', 'fxdriver.preconditions', 'goog.dom', 'goog.dom.TagName', 'goog.dom.selection', 'goog.log', 'goog.math.Coordinate', 'webdriver.atoms.element'], false);
goog.addDependency('../../../javascript/ie-driver/atoms.js', ['webdriver.ie'], ['bot.dom', 'bot.Error', 'bot.ErrorCode', 'bot.locators', 'bot.userAgent', 'goog.dom.TagName', 'goog.style'], false);
goog.addDependency('../../../javascript/ie-driver/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitCore.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitMockTimeout.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitTestManager.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitTestSuite.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitTracer.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/jsUnitVersionCheck.js', [], [], false);
goog.addDependency('../../../javascript/jsunit/app/xbDebug.js', [], [], false);
goog.addDependency('../../../javascript/remote/client.js', [], ['remote.ui.Client', 'webdriver.http.Executor', 'webdriver.http.XhrClient'], false);
goog.addDependency('../../../javascript/remote/deps.js', [], [], false);
goog.addDependency('../../../javascript/remote/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/remote/ui/actiondialog.js', ['remote.ui.ActionDialog'], ['goog.dom', 'goog.events', 'goog.ui.Component', 'goog.ui.Dialog'], false);
goog.addDependency('../../../javascript/remote/ui/banner.js', ['remote.ui.Banner'], ['goog.dom', 'goog.dom.TagName', 'goog.events', 'goog.events.EventType', 'goog.style', 'goog.ui.Component'], false);
goog.addDependency('../../../javascript/remote/ui/client.js', ['remote.ui.Client'], ['bot.response', 'goog.Disposable', 'goog.Uri', 'goog.array', 'goog.debug.Console', 'goog.events', 'goog.log', 'remote.ui.Banner', 'remote.ui.Event.Type', 'remote.ui.ScreenshotDialog', 'remote.ui.ServerInfo', 'remote.ui.SessionContainer', 'remote.ui.WebDriverScriptButton', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Session', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/remote/ui/controlblock.js', ['remote.ui.ControlBlock', 'remote.ui.createControlBlock', 'remote.ui.updateControlBlock'], ['goog.array', 'goog.dom', 'goog.dom.TagName', 'goog.ui.Component'], false);
goog.addDependency('../../../javascript/remote/ui/createsessiondialog.js', ['remote.ui.CreateSessionDialog'], ['goog.array', 'goog.dom', 'goog.dom.TagName', 'goog.events', 'goog.ui.Component', 'remote.ui.ActionDialog'], false);
goog.addDependency('../../../javascript/remote/ui/event.js', ['remote.ui.Event', 'remote.ui.Event.Type'], ['goog.events.Event'], false);
goog.addDependency('../../../javascript/remote/ui/fieldset.js', ['remote.ui.FieldSet'], ['goog.dom.TagName', 'goog.ui.Component'], false);
goog.addDependency('../../../javascript/remote/ui/jsontooltip.js', ['remote.ui.JsonTooltip'], ['goog.dom', 'goog.dom.TagName', 'goog.events', 'goog.events.EventType', 'goog.format.JsonPrettyPrinter', 'goog.ui.AdvancedTooltip'], false);
goog.addDependency('../../../javascript/remote/ui/openscriptdialog.js', ['remote.ui.OpenScriptDialog'], ['goog.dom', 'goog.dom.TagName', 'goog.dom.classlist', 'goog.events', 'goog.ui.Component', 'goog.ui.LabelInput', 'remote.ui.ActionDialog'], false);
goog.addDependency('../../../javascript/remote/ui/screenshotdialog.js', ['remote.ui.ScreenshotDialog', 'remote.ui.ScreenshotDialog.State'], ['goog.dom', 'goog.dom.TagName', 'goog.ui.Dialog'], false);
goog.addDependency('../../../javascript/remote/ui/serverinfo.js', ['remote.ui.ServerInfo'], ['goog.dom', 'goog.dom.TagName', 'goog.ui.Component'], false);
goog.addDependency('../../../javascript/remote/ui/sessioncontainer.js', ['remote.ui.SessionContainer', 'remote.ui.SessionContainer.SessionTab_'], ['goog.array', 'goog.dom.TagName', 'goog.events', 'goog.events.EventType', 'goog.structs.Map', 'goog.style', 'goog.ui.Component', 'goog.ui.Tab', 'goog.ui.TabBar', 'remote.ui.ControlBlock', 'remote.ui.CreateSessionDialog', 'remote.ui.Event', 'remote.ui.FieldSet', 'remote.ui.SessionView'], false);
goog.addDependency('../../../javascript/remote/ui/sessionview.js', ['remote.ui.SessionView'], ['goog.dom', 'goog.dom.TagName', 'goog.events', 'goog.math.Box', 'goog.style', 'goog.ui.Button', 'goog.ui.Component', 'goog.ui.Dialog', 'remote.ui.ControlBlock', 'remote.ui.Event', 'remote.ui.JsonTooltip'], false);
goog.addDependency('../../../javascript/remote/ui/webdriverscriptbutton.js', ['remote.ui.WebDriverScriptButton'], ['goog.events', 'goog.ui.Button', 'goog.ui.Component', 'remote.ui.Event', 'remote.ui.OpenScriptDialog'], false);
goog.addDependency('../../../javascript/safari-driver/alert.js', ['safaridriver.alert'], ['bot.ErrorCode'], false);
goog.addDependency('../../../javascript/safari-driver/client.js', ['safaridriver.client'], ['goog.Uri', 'goog.debug.DivConsole', 'goog.log', 'safaridriver.message.Connect'], false);
goog.addDependency('../../../javascript/safari-driver/command.js', ['safaridriver.Command', 'safaridriver.CommandHandler'], ['bot.json', 'webdriver.Command'], false);
goog.addDependency('../../../javascript/safari-driver/console.js', ['safaridriver.console'], ['goog.debug.LogManager', 'goog.debug.Logger', 'goog.debug.TextFormatter'], false);
goog.addDependency('../../../javascript/safari-driver/deps.js', [], [], false);
goog.addDependency('../../../javascript/safari-driver/dom.js', ['safaridriver.dom'], ['goog.array'], false);
goog.addDependency('../../../javascript/safari-driver/logging.js', ['safaridriver.logging.ForwardingHandler'], ['goog.Disposable', 'goog.array', 'goog.debug.LogManager', 'safaridriver.message.Log', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/safari-driver/tab.js', ['safaridriver.Tab'], ['goog.debug.Logger', 'goog.string', 'safaridriver.message.MessageTarget'], false);
goog.addDependency('../../../javascript/safari-driver/debug/debug.js', ['safaridriver.debug'], ['goog.dom', 'goog.dom.TagName', 'goog.log', 'goog.string', 'safaridriver.Command', 'safaridriver.console', 'safaridriver.message.Command', 'safaridriver.message.Log', 'safaridriver.message.MessageTarget', 'webdriver.Capabilities', 'webdriver.Session', 'webdriver.WebDriver', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/safari-driver/extension/commands.js', ['safaridriver.extension.commands'], ['bot.response', 'goog.Uri', 'goog.array', 'goog.log', 'goog.string', 'safaridriver.alert', 'safaridriver.extension.LogDb', 'safaridriver.extension.Tab', 'safaridriver.message.Alert', 'safaridriver.message.Load', 'webdriver.logging', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/extension/extension.js', ['safaridriver.extension'], ['bot.response', 'goog.asserts', 'goog.debug.LogManager', 'goog.log', 'safaridriver.console', 'safaridriver.extension.LogDb', 'safaridriver.extension.Server', 'safaridriver.extension.Session', 'safaridriver.extension.TabManager', 'safaridriver.logging.ForwardingHandler', 'safaridriver.message', 'safaridriver.message.Alert', 'safaridriver.message.Command', 'safaridriver.message.Connect', 'safaridriver.message.LoadModule', 'safaridriver.message.Response', 'webdriver.Session', 'webdriver.WebDriver', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/safari-driver/extension/logdb.js', ['safaridriver.extension.LogDb'], ['goog.log', 'goog.object', 'webdriver.logging', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/extension/server.js', ['safaridriver.extension.Server', 'safaridriver.extension.Server.CommandHandler'], ['bot.ErrorCode', 'bot.response', 'goog.Disposable', 'goog.log', 'goog.string', 'safaridriver.Command', 'safaridriver.alert', 'safaridriver.extension.commands', 'safaridriver.message.Command', 'safaridriver.message.Response', 'webdriver.CommandName', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/extension/session.js', ['safaridriver.extension.Session'], ['goog.string', 'goog.userAgent', 'goog.userAgent.product', 'webdriver.Capability', 'webdriver.Capabilities', 'webdriver.Session'], false);
goog.addDependency('../../../javascript/safari-driver/extension/tab.js', ['safaridriver.extension.Tab'], ['bot.response', 'goog.Uri', 'goog.asserts', 'goog.debug.Logger', 'safaridriver.Tab', 'safaridriver.message.Command', 'safaridriver.message.Load', 'safaridriver.message.PendingFrame', 'safaridriver.message.Response', 'safaridriver.message.Unload'], false);
goog.addDependency('../../../javascript/safari-driver/extension/tabmanager.js', ['safaridriver.extension.TabManager'], ['goog.array', 'goog.log', 'safaridriver.extension.Tab'], false);
goog.addDependency('../../../javascript/safari-driver/externs/common.js', [], [], false);
goog.addDependency('../../../javascript/safari-driver/externs/extension.js', [], [], false);
goog.addDependency('../../../javascript/safari-driver/externs/webcontent.js', [], [], false);
goog.addDependency('../../../javascript/safari-driver/inject/commandregistry.js', ['safaridriver.inject.CommandRegistry'], ['goog.array', 'goog.asserts', 'goog.log', 'safaridriver.inject.util', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/inject/encoder.js', ['safaridriver.inject.Encoder'], ['bot.Error', 'bot.ErrorCode', 'bot.inject', 'bot.response', 'goog.array', 'goog.dom', 'goog.dom.NodeType', 'goog.object', 'goog.string', 'safaridriver.inject.message.Encode', 'safaridriver.message.Response', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/inject/inject.js', ['safaridriver.inject'], ['bot.inject', 'goog.debug.LogManager', 'goog.log', 'safaridriver.inject.Tab', 'safaridriver.inject.commands.module', 'safaridriver.inject.message', 'safaridriver.inject.message.Encode', 'safaridriver.logging.ForwardingHandler', 'safaridriver.message', 'safaridriver.message.Connect', 'safaridriver.message.Response'], false);
goog.addDependency('../../../javascript/safari-driver/inject/tab.js', ['safaridriver.inject.Tab'], ['bot.Error', 'bot.ErrorCode', 'bot.inject', 'bot.json', 'bot.response', 'goog.asserts', 'goog.dom', 'goog.object', 'safaridriver.Command', 'safaridriver.Tab', 'safaridriver.alert', 'safaridriver.inject.CommandRegistry', 'safaridriver.inject.Encoder', 'safaridriver.inject.commands.TOP_FRAME_COMMANDS', 'safaridriver.inject.commands.util', 'safaridriver.inject.message', 'safaridriver.inject.message.Activate', 'safaridriver.inject.message.ActivateFrame', 'safaridriver.inject.message.ReactivateFrame', 'safaridriver.inject.util', 'safaridriver.message', 'safaridriver.message.Alert', 'safaridriver.message.Command', 'safaridriver.message.Load', 'safaridriver.message.LoadModule', 'safaridriver.message.Log', 'safaridriver.message.Message', 'safaridriver.message.MessageTarget', 'safaridriver.message.PendingFrame', 'safaridriver.message.Response', 'safaridriver.message.Unload', 'webdriver.CommandName', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/inject/util.js', ['safaridriver.inject.util'], ['bot.response', 'safaridriver.message.LoadModule', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/inject/commands/commands.js', ['safaridriver.inject.commands'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.action', 'bot.dom', 'bot.frame', 'bot.inject', 'bot.inject.cache', 'bot.locators', 'bot.window', 'goog.array', 'goog.log', 'goog.math.Coordinate', 'goog.math.Size', 'goog.net.cookies', 'goog.style', 'safaridriver.inject.CommandRegistry', 'safaridriver.inject.message.Activate', 'webdriver.atoms.element'], false);
goog.addDependency('../../../javascript/safari-driver/inject/commands/module.js', ['safaridriver.inject.commands.module'], ['goog.asserts', 'safaridriver.inject.CommandRegistry', 'webdriver.CommandName'], false);
goog.addDependency('../../../javascript/safari-driver/inject/commands/topcommands.js', ['safaridriver.inject.commands.TOP_FRAME_COMMANDS'], ['webdriver.CommandName'], false);
goog.addDependency('../../../javascript/safari-driver/inject/commands/util.js', ['safaridriver.inject.commands.util'], [], false);
goog.addDependency('../../../javascript/safari-driver/inject/message/encodemessage.js', ['safaridriver.inject.message.Encode'], ['safaridriver.message'], false);
goog.addDependency('../../../javascript/safari-driver/inject/message/framemessage.js', ['safaridriver.inject.message.Activate', 'safaridriver.inject.message.ActivateFrame', 'safaridriver.inject.message.ReactivateFrame'], ['safaridriver.message', 'safaridriver.message.BaseCommandMessage'], false);
goog.addDependency('../../../javascript/safari-driver/inject/message/message.js', ['safaridriver.inject.message'], [], false);
goog.addDependency('../../../javascript/safari-driver/inject/page/element.js', ['safaridriver.inject.page.element'], ['goog.object', 'safaridriver.inject.CommandRegistry', 'safaridriver.inject.page', 'safaridriver.inject.page.modules', 'webdriver.CommandName', 'webdriver.atoms.element'], false);
goog.addDependency('../../../javascript/safari-driver/inject/page/modules.js', ['safaridriver.inject.page.modules'], ['goog.asserts', 'safaridriver.inject.CommandRegistry', 'webdriver.CommandName'], false);
goog.addDependency('../../../javascript/safari-driver/inject/page/page.js', ['safaridriver.inject.page'], ['bot.Error', 'bot.ErrorCode', 'bot.response', 'goog.array', 'goog.debug.LogManager', 'goog.log', 'safaridriver.dom', 'safaridriver.inject.CommandRegistry', 'safaridriver.inject.Encoder', 'safaridriver.inject.message', 'safaridriver.inject.page.modules', 'safaridriver.logging.ForwardingHandler', 'safaridriver.message', 'safaridriver.message.Alert', 'safaridriver.message.Command', 'safaridriver.message.Load', 'safaridriver.message.MessageTarget', 'safaridriver.message.Response', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/inject/page/script.js', ['safaridriver.inject.page.script'], ['bot.Error', 'bot.ErrorCode', 'goog.object', 'safaridriver.dom', 'safaridriver.inject.CommandRegistry', 'safaridriver.inject.Encoder', 'safaridriver.inject.page.modules', 'webdriver.CommandName', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/safari-driver/message/alert.js', ['safaridriver.message.Alert'], ['safaridriver.message', 'safaridriver.message.Message'], false);
goog.addDependency('../../../javascript/safari-driver/message/command.js', ['safaridriver.message.BaseCommandMessage', 'safaridriver.message.Command', 'safaridriver.message.Response'], ['safaridriver.Command', 'safaridriver.message', 'safaridriver.message.Message'], false);
goog.addDependency('../../../javascript/safari-driver/message/connect.js', ['safaridriver.message.Connect'], ['safaridriver.message', 'safaridriver.message.Message'], false);
goog.addDependency('../../../javascript/safari-driver/message/load.js', ['safaridriver.message.BaseLoadMessage', 'safaridriver.message.Load', 'safaridriver.message.PendingFrame', 'safaridriver.message.Unload'], ['safaridriver.message', 'safaridriver.message.Message'], false);
goog.addDependency('../../../javascript/safari-driver/message/loadmodule.js', ['safaridriver.message.LoadModule'], ['safaridriver.message', 'safaridriver.message.Message'], false);
goog.addDependency('../../../javascript/safari-driver/message/logmessage.js', ['safaridriver.message.Log'], ['safaridriver.message', 'safaridriver.message.Message', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/safari-driver/message/message.js', ['safaridriver.message', 'safaridriver.message.Message'], ['bot.json', 'goog.asserts', 'goog.log', 'safaridriver.dom'], false);
goog.addDependency('../../../javascript/safari-driver/message/messagetarget.js', ['safaridriver.message.MessageTarget'], ['bot.json', 'goog.log', 'safaridriver.message', 'safaridriver.message.Message', 'webdriver.EventEmitter'], false);
goog.addDependency('../../../javascript/safari-driver/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/selenium-atoms/atoms.js', ['core.atoms'], ['webdriver.atoms.element', 'webdriver.atoms.storage.appcache', 'webdriver.atoms.storage.session'], false);
goog.addDependency('../../../javascript/selenium-atoms/browserbot.js', ['core.browserbot'], ['bot.dom', 'bot.locators', 'core.locators', 'core.patternMatcher'], false);
goog.addDependency('../../../javascript/selenium-atoms/core.js', ['core.Error'], ['goog.debug.Error'], false);
goog.addDependency('../../../javascript/selenium-atoms/events.js', ['core.events'], ['bot.dom', 'bot.events', 'bot.events.EventType', 'bot.events.MouseArgs', 'bot.userAgent', 'core.Error', 'core.locators', 'goog.dom', 'goog.dom.TagName', 'goog.style', 'goog.userAgent', 'goog.userAgent.product', 'goog.userAgent.product.isVersion'], false);
goog.addDependency('../../../javascript/selenium-atoms/filters.js', ['core.filters', 'core.filters.Strategy'], ['bot.dom', 'core.Error', 'goog.array'], false);
goog.addDependency('../../../javascript/selenium-atoms/firefox-chrome.js', ['core.firefox'], [], false);
goog.addDependency('../../../javascript/selenium-atoms/gettext.js', ['core.text.getText'], ['core.locators', 'core.text'], false);
goog.addDependency('../../../javascript/selenium-atoms/inject.js', ['core.inject'], ['bot.dom', 'bot.inject', 'core.firefox', 'goog.array', 'goog.json', 'goog.object'], false);
goog.addDependency('../../../javascript/selenium-atoms/locator_strategies.js', ['core.LocatorStrategies'], ['bot.inject.cache', 'bot.locators', 'core.filters', 'core.text', 'goog.dom', 'goog.string'], false);
goog.addDependency('../../../javascript/selenium-atoms/pattern_matcher.js', ['core.patternMatcher', 'core.patternMatcher.Strategy'], ['core.Error'], false);
goog.addDependency('../../../javascript/selenium-atoms/select.js', ['core.select', 'core.select.option'], ['bot.action', 'bot.dom', 'core.Error', 'core.locators', 'core.patternMatcher'], false);
goog.addDependency('../../../javascript/selenium-atoms/se_element.js', ['core.element'], ['bot.dom', 'core.Error', 'core.locators'], false);
goog.addDependency('../../../javascript/selenium-atoms/se_locators.js', ['core.locators', 'core.locators.Locator'], ['core.Error', 'core.LocatorStrategies', 'goog.dom.NodeType', 'goog.string'], false);
goog.addDependency('../../../javascript/selenium-atoms/text.js', ['core.text'], ['bot', 'bot.userAgent', 'core.patternMatcher', 'goog.dom', 'goog.dom.NodeType', 'goog.string', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/selenium-atoms/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/prototype.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/snapsie.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/cssQuery/cssQuery-p.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/cssQuery/src/cssQuery-level2.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/cssQuery/src/cssQuery-level3.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/cssQuery/src/cssQuery-standard.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/cssQuery/src/cssQuery.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/builder.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/controls.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/dragdrop.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/effects.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/scriptaculous.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/slider.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/lib/scriptaculous/unittest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/find_matching_child.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/htmlutils.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-api.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-browserbot.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-browserdetect.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-commandhandlers.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-executionloop.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-logging.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-remoterunner.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-testrunner.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/selenium-version.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/ui-element.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/ui-map-sample.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/user-extensions.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/scripts/xmlextras.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/AlertHandlingTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/AssertTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/BrowserBotFrameFinderTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/BrowserBotTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/CommandFactoryTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/CommandHandlerTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/ConfirmHandlingTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/CookieTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/ErrorCheckingCommandTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/HtmlUtilTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/OptionLocatorTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/PageBotAccessorTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/PatternMatcherTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/RemoteRunnerTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/SampleTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/SeleniumApiTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/SeleniumParameterTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/TestLoopHandleErrorTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/test/UIElementTest.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/xpath/dom.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/xpath/javascript-xpath-0.1.12.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/xpath/util.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/xpath/xmltoken.js', [], [], false);
goog.addDependency('../../../javascript/selenium-core/xpath/xpath.js', [], [], false);
goog.addDependency('../../../javascript/watir-atoms/watir.js', ['watir'], ['goog.dom.Range', 'goog.iter', 'goog.array'], false);
goog.addDependency('../../../javascript/webdriver/actionsequence.js', ['webdriver.ActionSequence'], ['goog.array', 'webdriver.Button', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Key'], false);
goog.addDependency('../../../javascript/webdriver/builder.js', ['webdriver.Builder'], ['goog.Uri', 'goog.userAgent', 'webdriver.Capabilities', 'webdriver.FirefoxDomExecutor', 'webdriver.WebDriver', 'webdriver.http.CorsClient', 'webdriver.http.Executor', 'webdriver.http.XhrClient'], false);
goog.addDependency('../../../javascript/webdriver/button.js', ['webdriver.Button'], [], false);
goog.addDependency('../../../javascript/webdriver/capabilities.js', ['webdriver.Browser', 'webdriver.Capabilities', 'webdriver.Capability', 'webdriver.ProxyConfig'], ['webdriver.Serializable', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/webdriver/command.js', ['webdriver.Command', 'webdriver.CommandExecutor', 'webdriver.CommandName'], [], false);
goog.addDependency('../../../javascript/webdriver/events.js', ['webdriver.EventEmitter'], [], false);
goog.addDependency('../../../javascript/webdriver/firefoxdomexecutor.js', ['webdriver.FirefoxDomExecutor'], ['bot.response', 'goog.userAgent.product', 'webdriver.Command', 'webdriver.CommandExecutor', 'webdriver.CommandName'], false);
goog.addDependency('../../../javascript/webdriver/key.js', ['webdriver.Key'], [], false);
goog.addDependency('../../../javascript/webdriver/locators.js', ['webdriver.By', 'webdriver.Locator', 'webdriver.Locator.Strategy'], ['goog.array', 'goog.object', 'goog.string'], false);
goog.addDependency('../../../javascript/webdriver/logging.js', ['webdriver.logging'], ['goog.debug.LogManager', 'goog.debug.LogRecord', 'goog.debug.Logger', 'goog.object', 'goog.string'], true);
goog.addDependency('../../../javascript/webdriver/promise.js', ['webdriver.promise'], ['goog.array', 'goog.asserts', 'goog.async.run', 'goog.async.throwException', 'goog.debug.Error', 'goog.object', 'webdriver.EventEmitter', 'webdriver.stacktrace'], true);
goog.addDependency('../../../javascript/webdriver/serializable.js', ['webdriver.Serializable'], [], false);
goog.addDependency('../../../javascript/webdriver/session.js', ['webdriver.Session'], ['webdriver.Capabilities'], false);
goog.addDependency('../../../javascript/webdriver/stacktrace.js', ['webdriver.stacktrace', 'webdriver.stacktrace.Snapshot'], ['goog.array', 'goog.string', 'goog.userAgent'], false);
goog.addDependency('../../../javascript/webdriver/touchsequence.js', ['webdriver.TouchSequence'], ['goog.array', 'webdriver.Command', 'webdriver.CommandName'], false);
goog.addDependency('../../../javascript/webdriver/until.js', ['webdriver.until'], ['bot.ErrorCode', 'goog.array', 'goog.string', 'webdriver.Locator'], false);
goog.addDependency('../../../javascript/webdriver/webdriver.js', ['webdriver.Alert', 'webdriver.AlertPromise', 'webdriver.FileDetector', 'webdriver.UnhandledAlertError', 'webdriver.WebDriver', 'webdriver.WebElement', 'webdriver.WebElementPromise'], ['bot.Error', 'bot.ErrorCode', 'bot.response', 'goog.array', 'goog.object', 'webdriver.ActionSequence', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.Key', 'webdriver.Locator', 'webdriver.Serializable', 'webdriver.Session', 'webdriver.TouchSequence', 'webdriver.logging', 'webdriver.promise', 'webdriver.until'], false);
goog.addDependency('../../../javascript/webdriver/atoms/element.js', ['webdriver.atoms.element'], ['bot.Keyboard.Keys', 'bot.action', 'bot.dom', 'goog.array', 'goog.dom.TagName', 'goog.math.Coordinate', 'goog.style', 'webdriver.Key'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inputs.js', ['webdriver.atoms.inputs'], ['bot.Keyboard', 'bot.Mouse', 'bot.action', 'goog.dom', 'goog.math.Coordinate', 'goog.style', 'webdriver.atoms.element'], false);
goog.addDependency('../../../javascript/webdriver/atoms/exports/inputs.js', [], ['webdriver.atoms.inputs'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/action.js', ['webdriver.atoms.inject.action'], ['bot.action', 'webdriver.atoms.element', 'webdriver.atoms.inject', 'webdriver.atoms.inputs'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/appcache.js', ['webdriver.atoms.inject.storage.appcache'], ['bot.inject', 'webdriver.atoms.storage.appcache'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/dom.js', ['webdriver.atoms.inject.dom'], ['bot.dom', 'bot.userAgent', 'webdriver.atoms.element', 'webdriver.atoms.inject'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/execute_script.js', ['webdriver.atoms.inject'], ['bot.inject', 'bot.inject.cache'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/find_element.js', ['webdriver.atoms.inject.locators'], ['bot.locators', 'bot.inject', 'webdriver.atoms.inject'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/frame.js', ['webdriver.atoms.inject.frame'], ['bot.frame', 'bot.inject.cache', 'webdriver.atoms.inject'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/local_storage.js', ['webdriver.atoms.inject.storage.local'], ['webdriver.atoms.inject', 'webdriver.atoms.storage.local'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/session_storage.js', ['webdriver.atoms.inject.storage.session'], ['webdriver.atoms.inject', 'webdriver.atoms.storage.session'], false);
goog.addDependency('../../../javascript/webdriver/atoms/inject/sql_database.js', ['webdriver.atoms.inject.storage.database'], ['bot.Error', 'bot.ErrorCode', 'bot.storage.database', 'webdriver.atoms.inject'], false);
goog.addDependency('../../../javascript/webdriver/atoms/storage/appcache.js', ['webdriver.atoms.storage.appcache'], ['bot.appcache'], false);
goog.addDependency('../../../javascript/webdriver/atoms/storage/local_storage.js', ['webdriver.atoms.storage.local'], ['bot.storage'], false);
goog.addDependency('../../../javascript/webdriver/atoms/storage/session_storage.js', ['webdriver.atoms.storage.session'], ['bot.storage'], false);
goog.addDependency('../../../javascript/webdriver/browser/browser.js', ['webdriver.browser'], ['goog.userAgent', 'goog.userAgent.product', 'webdriver.Browser', 'webdriver.Capabilities', 'webdriver.Capability', 'webdriver.Session', 'webdriver.WebDriver', 'webdriver.browser.CommandExecutor'], false);
goog.addDependency('../../../javascript/webdriver/browser/commandexecutor.js', ['webdriver.browser.CommandExecutor'], ['bot', 'bot.Error', 'bot.ErrorCode', 'bot.dom', 'bot.inject', 'bot.inject.cache', 'bot.locators', 'bot.response', 'bot.window', 'goog.Disposable', 'goog.events', 'goog.events.EventHandler', 'goog.events.EventType', 'goog.log', 'webdriver.CommandExecutor', 'webdriver.CommandName', 'webdriver.atoms.element', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/webdriver/exports/exports.js', [], ['bot.Error', 'bot.ErrorCode', 'bot.response', 'webdriver.ActionSequence', 'webdriver.Builder', 'webdriver.Button', 'webdriver.By', 'webdriver.Capabilities', 'webdriver.Capability', 'webdriver.Command', 'webdriver.CommandName', 'webdriver.EventEmitter', 'webdriver.Key', 'webdriver.Session', 'webdriver.WebDriver', 'webdriver.WebElement', 'webdriver.http.CorsClient', 'webdriver.http.Executor', 'webdriver.http.Request', 'webdriver.http.Response', 'webdriver.http.XhrClient', 'webdriver.promise', 'webdriver.stacktrace', 'webdriver.testing.assert', 'webdriver.testing.asserts'], false);
goog.addDependency('../../../javascript/webdriver/exports/exports_test.js', [], [], false);
goog.addDependency('../../../javascript/webdriver/externs/deps.js', [], [], false);
goog.addDependency('../../../javascript/webdriver/externs/externs.js', [], [], false);
goog.addDependency('../../../javascript/webdriver/http/corsclient.js', ['webdriver.http.CorsClient'], ['webdriver.http.Client', 'webdriver.http.Response'], false);
goog.addDependency('../../../javascript/webdriver/http/http.js', ['webdriver.http.Client', 'webdriver.http.Executor', 'webdriver.http.Request', 'webdriver.http.Response'], ['bot.ErrorCode', 'goog.array', 'webdriver.CommandExecutor', 'webdriver.CommandName', 'webdriver.logging', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/webdriver/http/xhrclient.js', ['webdriver.http.XhrClient'], ['goog.net.XmlHttp', 'webdriver.http.Client', 'webdriver.http.Response'], false);
goog.addDependency('../../../javascript/webdriver/test/builder_test.js', [], ['goog.testing.jsunit', 'webdriver.Builder'], false);
goog.addDependency('../../../javascript/webdriver/test/capabilities_test.js', [], ['goog.testing.jsunit', 'webdriver.Capabilities'], false);
goog.addDependency('../../../javascript/webdriver/test/events_test.js', [], ['goog.testing.jsunit', 'webdriver.EventEmitter'], false);
goog.addDependency('../../../javascript/webdriver/test/locators_test.js', [], ['goog.testing.jsunit', 'webdriver.By', 'webdriver.Locator', 'webdriver.Locator.Strategy', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/logging_test.js', [], ['goog.debug.LogRecord', 'goog.debug.Logger', 'goog.testing.jsunit', 'webdriver.logging'], false);
goog.addDependency('../../../javascript/webdriver/test/promise_error_test.js', [], ['goog.Promise', 'goog.async.run', 'goog.testing.jsunit', 'goog.userAgent', 'goog.userAgent.product', 'webdriver.promise', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/promise_flow_test.js', [], ['goog.array', 'goog.string', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.promise', 'webdriver.stacktrace.Snapshot', 'webdriver.stacktrace', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/promise_generator_test.js', ['webdriver.test.promise.generator.test'], ['goog.testing.jsunit', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/webdriver/test/promise_test.js', [], ['goog.testing.MockClock', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.promise', 'webdriver.stacktrace', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/stacktrace_test.js', [], ['bot.Error', 'bot.ErrorCode', 'goog.string', 'goog.testing.JsUnitException', 'goog.testing.PropertyReplacer', 'goog.testing.StrictMock', 'goog.testing.jsunit', 'goog.testing.stacktrace', 'webdriver.stacktrace', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/testutil.js', ['webdriver.test.testutil', 'webdriver.test.testutil.StubError'], ['goog.array', 'goog.debug.Error', 'goog.string', 'goog.testing.recordFunction', 'webdriver.stacktrace'], false);
goog.addDependency('../../../javascript/webdriver/test/testutil_test.js', [], ['goog.testing.jsunit', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/test_bootstrap.js', [], [], false);
goog.addDependency('../../../javascript/webdriver/test/until_test.js', ['webdriver.test.until_test'], ['bot.Error', 'bot.ErrorCode', 'bot.response', 'goog.array', 'goog.string', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.By', 'webdriver.CommandName', 'webdriver.WebDriver', 'webdriver.WebElement', 'webdriver.WebElementPromise', 'webdriver.until'], false);
goog.addDependency('../../../javascript/webdriver/test/webdriver_generator_test.js', ['webdriver.test.WebDriver.generator.test'], ['goog.testing.jsunit', 'webdriver.Session', 'webdriver.WebDriver'], false);
goog.addDependency('../../../javascript/webdriver/test/webdriver_test.js', [], ['bot.ErrorCode', 'goog.Promise', 'goog.functions', 'goog.testing.PropertyReplacer', 'goog.testing.MockControl', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.Capabilities', 'webdriver.Command', 'webdriver.CommandExecutor', 'webdriver.CommandName', 'webdriver.FileDetector', 'webdriver.WebDriver', 'webdriver.Serializable', 'webdriver.Session', 'webdriver.logging', 'webdriver.promise', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/e2e/setup.js', ['webdriver.test.e2e.setup'], ['goog.debug.TextFormatter', 'goog.dom', 'goog.log', 'goog.string', 'goog.userAgent.product', 'webdriver.browser', 'webdriver.testing.assert', 'webdriver.testing.jsunit'], false);
goog.addDependency('../../../javascript/webdriver/test/http/corsclient_test.js', [], ['goog.testing.MockControl', 'goog.testing.PropertyReplacer', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.http.CorsClient', 'webdriver.http.Request', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/http/http_test.js', [], ['bot.ErrorCode', 'goog.Uri', 'goog.testing.MockControl', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.Command', 'webdriver.http.Client', 'webdriver.http.Executor', 'webdriver.promise', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/http/xhrclient_test.js', [], ['goog.testing.MockControl', 'goog.testing.PropertyReplacer', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.http.Request', 'webdriver.http.XhrClient', 'webdriver.promise', 'webdriver.test.testutil'], false);
goog.addDependency('../../../javascript/webdriver/test/testing/asserts_test.js', [], ['goog.testing.jsunit', 'goog.userAgent', 'webdriver.test.testutil', 'webdriver.testing.assert', 'webdriver.testing.asserts'], false);
goog.addDependency('../../../javascript/webdriver/test/testing/client_test.js', [], ['goog.testing.MockControl', 'goog.testing.PropertyReplacer', 'goog.testing.jsunit', 'goog.userAgent', 'webdriver.testing.Client'], false);
goog.addDependency('../../../javascript/webdriver/test/testing/testcase_test.js', [], ['goog.Promise', 'goog.testing.MockControl', 'goog.testing.PropertyReplacer', 'goog.testing.mockmatchers', 'goog.testing.jsunit', 'goog.testing.recordFunction', 'goog.userAgent', 'webdriver.test.testutil', 'webdriver.testing.TestCase'], false);
goog.addDependency('../../../javascript/webdriver/testing/asserts.js', ['webdriver.testing.Assertion', 'webdriver.testing.ContainsMatcher', 'webdriver.testing.NegatedAssertion', 'webdriver.testing.assert', 'webdriver.testing.asserts'], ['goog.array', 'goog.labs.testing.CloseToMatcher', 'goog.labs.testing.EndsWithMatcher', 'goog.labs.testing.EqualToMatcher', 'goog.labs.testing.EqualsMatcher', 'goog.labs.testing.GreaterThanEqualToMatcher', 'goog.labs.testing.GreaterThanMatcher', 'goog.labs.testing.LessThanEqualToMatcher', 'goog.labs.testing.LessThanMatcher', 'goog.labs.testing.InstanceOfMatcher', 'goog.labs.testing.IsNotMatcher', 'goog.labs.testing.IsNullMatcher', 'goog.labs.testing.IsNullOrUndefinedMatcher', 'goog.labs.testing.IsUndefinedMatcher', 'goog.labs.testing.Matcher', 'goog.labs.testing.ObjectEqualsMatcher', 'goog.labs.testing.RegexMatcher', 'goog.labs.testing.StartsWithMatcher', 'goog.labs.testing.assertThat', 'goog.string', 'webdriver.promise'], false);
goog.addDependency('../../../javascript/webdriver/testing/client.js', ['webdriver.testing.Client'], ['goog.json', 'goog.net.XmlHttp'], false);
goog.addDependency('../../../javascript/webdriver/testing/jsunit.js', ['webdriver.testing.jsunit', 'webdriver.testing.jsunit.TestRunner'], ['goog.testing.TestRunner', 'webdriver.testing.Client', 'webdriver.testing.TestCase'], false);
goog.addDependency('../../../javascript/webdriver/testing/testcase.js', ['webdriver.testing.TestCase'], ['goog.testing.TestCase', 'webdriver.promise', 'webdriver.testing.asserts'], false);
goog.addDependency('../../../javascript/webdriver/testing/window.js', ['webdriver.testing.Window'], ['goog.string', 'webdriver.promise'], false);
goog.addDependency('../../js/wgxpath/binaryExpr.js', ['wgxpath.BinaryExpr'], ['wgxpath.DataType', 'wgxpath.Expr', 'wgxpath.Node'], false);
goog.addDependency('../../js/wgxpath/context.js', ['wgxpath.Context'], [], false);
goog.addDependency('../../js/wgxpath/dataType.js', ['wgxpath.DataType'], [], false);
goog.addDependency('../../js/wgxpath/export.js', [], ['wgxpath'], false);
goog.addDependency('../../js/wgxpath/expr.js', ['wgxpath.Expr'], ['wgxpath.NodeSet'], false);
goog.addDependency('../../js/wgxpath/filterExpr.js', ['wgxpath.FilterExpr'], ['wgxpath.Expr'], false);
goog.addDependency('../../js/wgxpath/functionCall.js', ['wgxpath.FunctionCall'], ['goog.array', 'goog.dom', 'goog.dom.NodeType', 'goog.string', 'wgxpath.Expr', 'wgxpath.Node', 'wgxpath.NodeSet', 'wgxpath.userAgent'], false);
goog.addDependency('../../js/wgxpath/ieAttrWrapper.js', ['wgxpath.IEAttrWrapper'], ['goog.dom.NodeType', 'wgxpath.userAgent'], false);
goog.addDependency('../../js/wgxpath/kindTest.js', ['wgxpath.KindTest'], ['goog.dom.NodeType', 'wgxpath.NodeTest'], false);
goog.addDependency('../../js/wgxpath/lexer.js', ['wgxpath.Lexer'], [], false);
goog.addDependency('../../js/wgxpath/literal.js', ['wgxpath.Literal'], ['wgxpath.Expr'], false);
goog.addDependency('../../js/wgxpath/nameTest.js', ['wgxpath.NameTest'], ['goog.dom.NodeType', 'wgxpath.NodeTest'], false);
goog.addDependency('../../js/wgxpath/node.js', ['wgxpath.Node'], ['goog.array', 'goog.dom.NodeType', 'goog.userAgent', 'wgxpath.IEAttrWrapper', 'wgxpath.userAgent'], false);
goog.addDependency('../../js/wgxpath/nodeset.js', ['wgxpath.NodeSet'], ['goog.dom', 'wgxpath.Node'], false);
goog.addDependency('../../js/wgxpath/nodeTest.js', ['wgxpath.NodeTest'], [], false);
goog.addDependency('../../js/wgxpath/nsResolver.js', ['wgxpath.nsResolver'], ['goog.dom.NodeType'], false);
goog.addDependency('../../js/wgxpath/number.js', ['wgxpath.Number'], ['wgxpath.Expr'], false);
goog.addDependency('../../js/wgxpath/parser.js', ['wgxpath.Parser'], ['wgxpath.BinaryExpr', 'wgxpath.FilterExpr', 'wgxpath.FunctionCall', 'wgxpath.KindTest', 'wgxpath.Literal', 'wgxpath.NameTest', 'wgxpath.Number', 'wgxpath.PathExpr', 'wgxpath.Predicates', 'wgxpath.Step', 'wgxpath.UnaryExpr', 'wgxpath.UnionExpr'], false);
goog.addDependency('../../js/wgxpath/pathExpr.js', ['wgxpath.PathExpr'], ['goog.array', 'goog.dom.NodeType', 'wgxpath.Context', 'wgxpath.DataType', 'wgxpath.Expr', 'wgxpath.NodeSet'], false);
goog.addDependency('../../js/wgxpath/predicates.js', ['wgxpath.Predicates'], ['goog.array', 'wgxpath.Context', 'wgxpath.Expr'], false);
goog.addDependency('../../js/wgxpath/step.js', ['wgxpath.Step'], ['goog.array', 'goog.dom.NodeType', 'wgxpath.DataType', 'wgxpath.Expr', 'wgxpath.KindTest', 'wgxpath.Node', 'wgxpath.NodeSet', 'wgxpath.Predicates', 'wgxpath.userAgent'], false);
goog.addDependency('../../js/wgxpath/test_js_deps.js', [], [], false);
goog.addDependency('../../js/wgxpath/unaryExpr.js', ['wgxpath.UnaryExpr'], ['wgxpath.DataType', 'wgxpath.Expr'], false);
goog.addDependency('../../js/wgxpath/unionExpr.js', ['wgxpath.UnionExpr'], ['goog.array', 'wgxpath.DataType', 'wgxpath.Expr', 'wgxpath.NodeSet'], false);
goog.addDependency('../../js/wgxpath/userAgent.js', ['wgxpath.userAgent'], ['goog.userAgent'], false);
goog.addDependency('../../js/wgxpath/wgxpath.js', ['wgxpath'], ['wgxpath.Context', 'wgxpath.IEAttrWrapper', 'wgxpath.Lexer', 'wgxpath.NodeSet', 'wgxpath.Parser', 'wgxpath.nsResolver'], false);
